# Configuration for GitHub's secret scanning
# Exclude test files and directories from secret scanning
# These contain deliberately crafted test patterns that look like secrets

paths-ignore:
  - "attestation/secretscan/testdata/**"
  - "attestation/secretscan/secretscan_test.go"
  - "attestation/secretscan/attestor_test.go"
  - "attestation/secretscan/scanner_test.go"
  - "attestation/secretscan/encoding_test.go"
  - "attestation/secretscan/secretscan_fuzz_test.go"
  - "attestation/secretscan/examples/**"