/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * aws pre type attestation
 */
export interface AwsAttestation {
  devpayProductCodes: string[];
  marketplaceProductCodes: string[];
  availabilityZone: string;
  privateIp: string;
  version: string;
  region: string;
  instanceId: string;
  billingProducts: string[];
  instanceType: string;
  accountId: string;
  pendingTime: string;
  imageId: string;
  kernelId: string;
  ramdiskId: string;
  architecture: string;
  rawiid: string;
  rawsig: string;
  publickey: string;
}
