/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * command-run internal type attestation
 */
export interface CommandRunAttestation {
  cmd: string[];
  stdout?: string;
  stderr?: string;
  exitcode: number;
  processes?: {
    program?: string;
    processid: number;
    parentpid: number;
    programdigest?: {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` ".*".
       */
      [k: string]: string;
    };
    comm?: string;
    cmdline?: string;
    exedigest?: {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` ".*".
       */
      [k: string]: string;
    };
    openedfiles?: {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` ".*".
       */
      [k: string]: {
        /**
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` ".*".
         */
        [k: string]: string;
      };
    };
    environ?: string;
    specbypassisvuln?: boolean;
  }[];
}
