/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * gcp-iit pre type attestation
 */
export interface GcpIitAttestation {
  claims: {
    [k: string]: unknown;
  };
  verifiedBy?: {
    jwksUrl: string;
    jwk: {
      Key: true;
      KeyID: string;
      Algorithm: string;
      Use: string;
      Certificates: {
        Raw: string;
        RawTBSCertificate: string;
        RawSubjectPublicKeyInfo: string;
        RawSubject: string;
        RawIssuer: string;
        Signature: string;
        SignatureAlgorithm: number;
        PublicKeyAlgorithm: number;
        PublicKey: true;
        Version: number;
        SerialNumber: {};
        Issuer: {
          Country: string[];
          Organization: string[];
          OrganizationalUnit: string[];
          Locality: string[];
          Province: string[];
          StreetAddress: string[];
          PostalCode: string[];
          SerialNumber: string;
          CommonName: string;
          Names: {
            Type: number[];
            Value: true;
          }[];
          ExtraNames: {
            Type: number[];
            Value: true;
          }[];
        };
        Subject: {
          Country: string[];
          Organization: string[];
          OrganizationalUnit: string[];
          Locality: string[];
          Province: string[];
          StreetAddress: string[];
          PostalCode: string[];
          SerialNumber: string;
          CommonName: string;
          Names: {
            Type: number[];
            Value: true;
          }[];
          ExtraNames: {
            Type: number[];
            Value: true;
          }[];
        };
        NotBefore: string;
        NotAfter: string;
        KeyUsage: number;
        Extensions: {
          Id: number[];
          Critical: boolean;
          Value: string;
        }[];
        ExtraExtensions: {
          Id: number[];
          Critical: boolean;
          Value: string;
        }[];
        UnhandledCriticalExtensions: number[][];
        ExtKeyUsage: number[];
        UnknownExtKeyUsage: number[][];
        BasicConstraintsValid: boolean;
        IsCA: boolean;
        MaxPathLen: number;
        MaxPathLenZero: boolean;
        SubjectKeyId: string;
        AuthorityKeyId: string;
        OCSPServer: string[];
        IssuingCertificateURL: string[];
        DNSNames: string[];
        EmailAddresses: string[];
        IPAddresses: string[];
        URIs: string[];
        PermittedDNSDomainsCritical: boolean;
        PermittedDNSDomains: string[];
        ExcludedDNSDomains: string[];
        PermittedIPRanges: {
          IP: string;
          Mask: string;
        }[];
        ExcludedIPRanges: {
          IP: string;
          Mask: string;
        }[];
        PermittedEmailAddresses: string[];
        ExcludedEmailAddresses: string[];
        PermittedURIDomains: string[];
        ExcludedURIDomains: string[];
        CRLDistributionPoints: string[];
        PolicyIdentifiers: number[][];
      }[];
      CertificatesURL: string;
      CertificateThumbprintSHA1: string;
      CertificateThumbprintSHA256: string;
    };
  };
}
