/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * maven pre type attestation
 */
export interface MavenAttestation {
  groupid: string;
  artifactid: string;
  version: string;
  projectname: string;
  dependencies: {
    groupid: string;
    artifactid: string;
    version: string;
    scope: string;
  }[];
}
