/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * sarif post type attestation
 */
export interface SarifAttestation {
  report: {
    properties?: {
      [k: string]: unknown;
    };
    version: string;
    $schema: string;
    runs: {
      properties?: {
        [k: string]: unknown;
      };
      tool: {
        properties?: {
          [k: string]: unknown;
        };
        driver: {
          properties?: {
            [k: string]: unknown;
          };
          name: string;
          version?: string;
          informationUri: string;
          notifications?: {
            properties?: {
              [k: string]: unknown;
            };
            id: string;
            name?: string;
            shortDescription: {
              properties?: {
                [k: string]: unknown;
              };
              text?: string;
              markdown?: string;
            };
            fullDescription?: {
              properties?: {
                [k: string]: unknown;
              };
              text?: string;
              markdown?: string;
            };
            defaultConfiguration?: {
              enabled?: boolean;
              level?: true;
              parameters?: {
                properties?: {
                  [k: string]: unknown;
                };
              };
              properties?: {
                properties?: {
                  [k: string]: unknown;
                };
              };
              rank?: number;
            };
            helpUri?: string;
            help?: {
              properties?: {
                [k: string]: unknown;
              };
              text?: string;
              markdown?: string;
            };
          }[];
          rules?: {
            properties?: {
              [k: string]: unknown;
            };
            id: string;
            name?: string;
            shortDescription: {
              properties?: {
                [k: string]: unknown;
              };
              text?: string;
              markdown?: string;
            };
            fullDescription?: {
              properties?: {
                [k: string]: unknown;
              };
              text?: string;
              markdown?: string;
            };
            defaultConfiguration?: {
              enabled?: boolean;
              level?: true;
              parameters?: {
                properties?: {
                  [k: string]: unknown;
                };
              };
              properties?: {
                properties?: {
                  [k: string]: unknown;
                };
              };
              rank?: number;
            };
            helpUri?: string;
            help?: {
              properties?: {
                [k: string]: unknown;
              };
              text?: string;
              markdown?: string;
            };
          }[];
          taxa?: {
            properties?: {
              [k: string]: unknown;
            };
            id: string;
            name?: string;
            shortDescription: {
              properties?: {
                [k: string]: unknown;
              };
              text?: string;
              markdown?: string;
            };
            fullDescription?: {
              properties?: {
                [k: string]: unknown;
              };
              text?: string;
              markdown?: string;
            };
            defaultConfiguration?: {
              enabled?: boolean;
              level?: true;
              parameters?: {
                properties?: {
                  [k: string]: unknown;
                };
              };
              properties?: {
                properties?: {
                  [k: string]: unknown;
                };
              };
              rank?: number;
            };
            helpUri?: string;
            help?: {
              properties?: {
                [k: string]: unknown;
              };
              text?: string;
              markdown?: string;
            };
          }[];
        };
      };
      invocations?: {
        properties?: {
          [k: string]: unknown;
        };
        startTimeUtc?: string;
        endTimeUtc?: string;
        executionSuccessful: boolean;
        workingDirectory?: {
          properties?: {
            [k: string]: unknown;
          };
          uri?: string;
          uriBaseId?: string;
          index?: number;
          description?: {
            properties?: {
              [k: string]: unknown;
            };
            text?: string;
            markdown?: string;
            id?: string;
            arguments?: string[];
          };
        };
      }[];
      artifacts?: {
        properties?: {
          [k: string]: unknown;
        };
        location?: {
          properties?: {
            [k: string]: unknown;
          };
          uri?: string;
          uriBaseId?: string;
          index?: number;
          description?: {
            properties?: {
              [k: string]: unknown;
            };
            text?: string;
            markdown?: string;
            id?: string;
            arguments?: string[];
          };
        };
        parentIndex?: number;
        offset?: number;
        length: number;
        roles?: string[];
        mimeType?: string;
        contents?: {
          properties?: {
            [k: string]: unknown;
          };
          text?: string;
          binary?: string;
          rendered?: {
            properties?: {
              [k: string]: unknown;
            };
            text?: string;
            markdown?: string;
          };
        };
        encoding?: string;
        sourceLanguage?: string;
        hashes?: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` ".*".
           */
          [k: string]: string;
        };
        lastModifiedTimeUtc?: string;
        description?: {
          properties?: {
            [k: string]: unknown;
          };
          text?: string;
          markdown?: string;
          id?: string;
          arguments?: string[];
        };
      }[];
      results: {
        properties?: {
          [k: string]: unknown;
        };
        guid?: string;
        correlationGuid?: string;
        ruleId?: string;
        ruleIndex?: number;
        rule?: {
          properties?: {
            [k: string]: unknown;
          };
          id?: string;
          index?: number;
          guid?: string;
          toolComponent?: {
            properties?: {
              [k: string]: unknown;
            };
            name: string;
            index: number;
            guid: string;
          };
        };
        taxa?: {
          properties?: {
            [k: string]: unknown;
          };
          id?: string;
          index?: number;
          guid?: string;
          toolComponent?: {
            properties?: {
              [k: string]: unknown;
            };
            name: string;
            index: number;
            guid: string;
          };
        }[];
        kind?: string;
        level?: string;
        message: {
          properties?: {
            [k: string]: unknown;
          };
          text?: string;
          markdown?: string;
          id?: string;
          arguments?: string[];
        };
        locations?: {
          properties?: {
            [k: string]: unknown;
          };
          id?: number;
          physicalLocation?: {
            properties?: {
              [k: string]: unknown;
            };
            artifactLocation?: {
              properties?: {
                [k: string]: unknown;
              };
              uri?: string;
              uriBaseId?: string;
              index?: number;
              description?: {
                properties?: {
                  [k: string]: unknown;
                };
                text?: string;
                markdown?: string;
                id?: string;
                arguments?: string[];
              };
            };
            region?: {
              properties?: {
                [k: string]: unknown;
              };
              startLine?: number;
              startColumn?: number;
              endLine?: number;
              endColumn?: number;
              charOffset?: number;
              charLength?: number;
              byteOffset?: number;
              byteLength?: number;
              snippet?: {
                properties?: {
                  [k: string]: unknown;
                };
                text?: string;
                binary?: string;
                rendered?: {
                  properties?: {
                    [k: string]: unknown;
                  };
                  text?: string;
                  markdown?: string;
                };
              };
              message?: {
                properties?: {
                  [k: string]: unknown;
                };
                text?: string;
                markdown?: string;
                id?: string;
                arguments?: string[];
              };
              sourceLanguage?: string;
            };
            contextRegion?: {
              properties?: {
                [k: string]: unknown;
              };
              startLine?: number;
              startColumn?: number;
              endLine?: number;
              endColumn?: number;
              charOffset?: number;
              charLength?: number;
              byteOffset?: number;
              byteLength?: number;
              snippet?: {
                properties?: {
                  [k: string]: unknown;
                };
                text?: string;
                binary?: string;
                rendered?: {
                  properties?: {
                    [k: string]: unknown;
                  };
                  text?: string;
                  markdown?: string;
                };
              };
              message?: {
                properties?: {
                  [k: string]: unknown;
                };
                text?: string;
                markdown?: string;
                id?: string;
                arguments?: string[];
              };
              sourceLanguage?: string;
            };
            address?: {
              properties?: {
                [k: string]: unknown;
              };
              index?: number;
              absoluteAddress?: number;
              relativeAddress?: number;
              offsetFromParent?: number;
              length?: number;
              name?: string;
              fullyQualifiedName?: string;
              kind?: string;
              parentIndex?: number;
            };
          };
          logicalLocations?: {
            properties?: {
              [k: string]: unknown;
            };
            index?: number;
            name?: string;
            fullyQualifiedName?: string;
            decoratedName?: string;
            kind?: string;
            parentIndex?: number;
          }[];
          message?: {
            properties?: {
              [k: string]: unknown;
            };
            text?: string;
            markdown?: string;
            id?: string;
            arguments?: string[];
          };
          annotations?: {
            properties?: {
              [k: string]: unknown;
            };
            startLine?: number;
            startColumn?: number;
            endLine?: number;
            endColumn?: number;
            charOffset?: number;
            charLength?: number;
            byteOffset?: number;
            byteLength?: number;
            snippet?: {
              properties?: {
                [k: string]: unknown;
              };
              text?: string;
              binary?: string;
              rendered?: {
                properties?: {
                  [k: string]: unknown;
                };
                text?: string;
                markdown?: string;
              };
            };
            message?: {
              properties?: {
                [k: string]: unknown;
              };
              text?: string;
              markdown?: string;
              id?: string;
              arguments?: string[];
            };
            sourceLanguage?: string;
          }[];
          relationships?: {
            properties?: {
              [k: string]: unknown;
            };
            target: number;
            kinds?: string[];
            description?: {
              properties?: {
                [k: string]: unknown;
              };
              text?: string;
              markdown?: string;
              id?: string;
              arguments?: string[];
            };
          }[];
        }[];
        analysisTarget?: {
          properties?: {
            [k: string]: unknown;
          };
          uri?: string;
          uriBaseId?: string;
          index?: number;
          description?: {
            properties?: {
              [k: string]: unknown;
            };
            text?: string;
            markdown?: string;
            id?: string;
            arguments?: string[];
          };
        };
        fingerprints?: {
          [k: string]: unknown;
        };
        partialFingerprints?: {
          [k: string]: unknown;
        };
        relatedLocations?: {
          properties?: {
            [k: string]: unknown;
          };
          id?: number;
          physicalLocation?: {
            properties?: {
              [k: string]: unknown;
            };
            artifactLocation?: {
              properties?: {
                [k: string]: unknown;
              };
              uri?: string;
              uriBaseId?: string;
              index?: number;
              description?: {
                properties?: {
                  [k: string]: unknown;
                };
                text?: string;
                markdown?: string;
                id?: string;
                arguments?: string[];
              };
            };
            region?: {
              properties?: {
                [k: string]: unknown;
              };
              startLine?: number;
              startColumn?: number;
              endLine?: number;
              endColumn?: number;
              charOffset?: number;
              charLength?: number;
              byteOffset?: number;
              byteLength?: number;
              snippet?: {
                properties?: {
                  [k: string]: unknown;
                };
                text?: string;
                binary?: string;
                rendered?: {
                  properties?: {
                    [k: string]: unknown;
                  };
                  text?: string;
                  markdown?: string;
                };
              };
              message?: {
                properties?: {
                  [k: string]: unknown;
                };
                text?: string;
                markdown?: string;
                id?: string;
                arguments?: string[];
              };
              sourceLanguage?: string;
            };
            contextRegion?: {
              properties?: {
                [k: string]: unknown;
              };
              startLine?: number;
              startColumn?: number;
              endLine?: number;
              endColumn?: number;
              charOffset?: number;
              charLength?: number;
              byteOffset?: number;
              byteLength?: number;
              snippet?: {
                properties?: {
                  [k: string]: unknown;
                };
                text?: string;
                binary?: string;
                rendered?: {
                  properties?: {
                    [k: string]: unknown;
                  };
                  text?: string;
                  markdown?: string;
                };
              };
              message?: {
                properties?: {
                  [k: string]: unknown;
                };
                text?: string;
                markdown?: string;
                id?: string;
                arguments?: string[];
              };
              sourceLanguage?: string;
            };
            address?: {
              properties?: {
                [k: string]: unknown;
              };
              index?: number;
              absoluteAddress?: number;
              relativeAddress?: number;
              offsetFromParent?: number;
              length?: number;
              name?: string;
              fullyQualifiedName?: string;
              kind?: string;
              parentIndex?: number;
            };
          };
          logicalLocations?: {
            properties?: {
              [k: string]: unknown;
            };
            index?: number;
            name?: string;
            fullyQualifiedName?: string;
            decoratedName?: string;
            kind?: string;
            parentIndex?: number;
          }[];
          message?: {
            properties?: {
              [k: string]: unknown;
            };
            text?: string;
            markdown?: string;
            id?: string;
            arguments?: string[];
          };
          annotations?: {
            properties?: {
              [k: string]: unknown;
            };
            startLine?: number;
            startColumn?: number;
            endLine?: number;
            endColumn?: number;
            charOffset?: number;
            charLength?: number;
            byteOffset?: number;
            byteLength?: number;
            snippet?: {
              properties?: {
                [k: string]: unknown;
              };
              text?: string;
              binary?: string;
              rendered?: {
                properties?: {
                  [k: string]: unknown;
                };
                text?: string;
                markdown?: string;
              };
            };
            message?: {
              properties?: {
                [k: string]: unknown;
              };
              text?: string;
              markdown?: string;
              id?: string;
              arguments?: string[];
            };
            sourceLanguage?: string;
          }[];
          relationships?: {
            properties?: {
              [k: string]: unknown;
            };
            target: number;
            kinds?: string[];
            description?: {
              properties?: {
                [k: string]: unknown;
              };
              text?: string;
              markdown?: string;
              id?: string;
              arguments?: string[];
            };
          }[];
        }[];
        suppressions?: {
          properties?: {
            [k: string]: unknown;
          };
          kind: string;
          status: string;
          location: {
            properties?: {
              [k: string]: unknown;
            };
            id?: number;
            physicalLocation?: {
              properties?: {
                [k: string]: unknown;
              };
              artifactLocation?: {
                properties?: {
                  [k: string]: unknown;
                };
                uri?: string;
                uriBaseId?: string;
                index?: number;
                description?: {
                  properties?: {
                    [k: string]: unknown;
                  };
                  text?: string;
                  markdown?: string;
                  id?: string;
                  arguments?: string[];
                };
              };
              region?: {
                properties?: {
                  [k: string]: unknown;
                };
                startLine?: number;
                startColumn?: number;
                endLine?: number;
                endColumn?: number;
                charOffset?: number;
                charLength?: number;
                byteOffset?: number;
                byteLength?: number;
                snippet?: {
                  properties?: {
                    [k: string]: unknown;
                  };
                  text?: string;
                  binary?: string;
                  rendered?: {
                    properties?: {
                      [k: string]: unknown;
                    };
                    text?: string;
                    markdown?: string;
                  };
                };
                message?: {
                  properties?: {
                    [k: string]: unknown;
                  };
                  text?: string;
                  markdown?: string;
                  id?: string;
                  arguments?: string[];
                };
                sourceLanguage?: string;
              };
              contextRegion?: {
                properties?: {
                  [k: string]: unknown;
                };
                startLine?: number;
                startColumn?: number;
                endLine?: number;
                endColumn?: number;
                charOffset?: number;
                charLength?: number;
                byteOffset?: number;
                byteLength?: number;
                snippet?: {
                  properties?: {
                    [k: string]: unknown;
                  };
                  text?: string;
                  binary?: string;
                  rendered?: {
                    properties?: {
                      [k: string]: unknown;
                    };
                    text?: string;
                    markdown?: string;
                  };
                };
                message?: {
                  properties?: {
                    [k: string]: unknown;
                  };
                  text?: string;
                  markdown?: string;
                  id?: string;
                  arguments?: string[];
                };
                sourceLanguage?: string;
              };
              address?: {
                properties?: {
                  [k: string]: unknown;
                };
                index?: number;
                absoluteAddress?: number;
                relativeAddress?: number;
                offsetFromParent?: number;
                length?: number;
                name?: string;
                fullyQualifiedName?: string;
                kind?: string;
                parentIndex?: number;
              };
            };
            logicalLocations?: {
              properties?: {
                [k: string]: unknown;
              };
              index?: number;
              name?: string;
              fullyQualifiedName?: string;
              decoratedName?: string;
              kind?: string;
              parentIndex?: number;
            }[];
            message?: {
              properties?: {
                [k: string]: unknown;
              };
              text?: string;
              markdown?: string;
              id?: string;
              arguments?: string[];
            };
            annotations?: {
              properties?: {
                [k: string]: unknown;
              };
              startLine?: number;
              startColumn?: number;
              endLine?: number;
              endColumn?: number;
              charOffset?: number;
              charLength?: number;
              byteOffset?: number;
              byteLength?: number;
              snippet?: {
                properties?: {
                  [k: string]: unknown;
                };
                text?: string;
                binary?: string;
                rendered?: {
                  properties?: {
                    [k: string]: unknown;
                  };
                  text?: string;
                  markdown?: string;
                };
              };
              message?: {
                properties?: {
                  [k: string]: unknown;
                };
                text?: string;
                markdown?: string;
                id?: string;
                arguments?: string[];
              };
              sourceLanguage?: string;
            }[];
            relationships?: {
              properties?: {
                [k: string]: unknown;
              };
              target: number;
              kinds?: string[];
              description?: {
                properties?: {
                  [k: string]: unknown;
                };
                text?: string;
                markdown?: string;
                id?: string;
                arguments?: string[];
              };
            }[];
          };
          guid: string;
          justification: string;
        }[];
        baselineState?: string;
        rank?: number;
        workItemUris?: string[];
        hostedViewerUri?: string;
        fixes?: {
          properties?: {
            [k: string]: unknown;
          };
          description?: {
            properties?: {
              [k: string]: unknown;
            };
            text?: string;
            markdown?: string;
            id?: string;
            arguments?: string[];
          };
          artifactChanges: {
            properties?: {
              [k: string]: unknown;
            };
            artifactLocation: {
              properties?: {
                [k: string]: unknown;
              };
              uri?: string;
              uriBaseId?: string;
              index?: number;
              description?: {
                properties?: {
                  [k: string]: unknown;
                };
                text?: string;
                markdown?: string;
                id?: string;
                arguments?: string[];
              };
            };
            replacements: {
              properties?: {
                [k: string]: unknown;
              };
              deletedRegion: {
                properties?: {
                  [k: string]: unknown;
                };
                startLine?: number;
                startColumn?: number;
                endLine?: number;
                endColumn?: number;
                charOffset?: number;
                charLength?: number;
                byteOffset?: number;
                byteLength?: number;
                snippet?: {
                  properties?: {
                    [k: string]: unknown;
                  };
                  text?: string;
                  binary?: string;
                  rendered?: {
                    properties?: {
                      [k: string]: unknown;
                    };
                    text?: string;
                    markdown?: string;
                  };
                };
                message?: {
                  properties?: {
                    [k: string]: unknown;
                  };
                  text?: string;
                  markdown?: string;
                  id?: string;
                  arguments?: string[];
                };
                sourceLanguage?: string;
              };
              insertedContent?: {
                properties?: {
                  [k: string]: unknown;
                };
                text?: string;
                binary?: string;
                rendered?: {
                  properties?: {
                    [k: string]: unknown;
                  };
                  text?: string;
                  markdown?: string;
                };
              };
            }[];
          }[];
        }[];
        occurrenceCount?: number;
      }[];
    }[];
  };
  reportFileName: string;
  reportDigestSet: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` ".*".
     */
    [k: string]: string;
  };
}
