/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * sbom pre type attestation
 */
export interface SbomAttestation {
  spdxVersion?: string;
  dataLicense?: string;
  SPDXID?: string;
  name?: string;
  documentNamespace?: string;
  creationInfo?: {
    comment?: string;
    created?: string;
    creators?: string[];
    licenseListVersion?: string;
  };
  packages?: {
    name?: string;
    SPDXID?: string;
    versionInfo?: string;
    supplier?: string;
    downloadLocation?: string;
    filesAnalyzed: boolean;
    checksums: {
      algorithm: string;
      checksumValue: string;
    }[];
    homepage?: string;
    licenseConcluded?: string;
    licenseDeclared?: string;
    copyrightText?: string;
    licenseComments?: string;
    comment?: string;
  }[];
  relationships?: {
    spdxElementId?: string;
    relatedSpdxElement?: string;
    relationshipType?: string;
  }[];
  hasExtractedLicensingInfos?: {
    licenseId?: string;
    extractedText?: string;
    name?: string;
    comment?: string;
  }[];
}
