/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * scorecard post type attestation
 */
export interface ScorecardAttestation {
  scorecard: {
    date: string;
    repo: {
      name: string;
      commit: string;
    };
    scorecard: {
      version: string;
      commit: string;
    };
    score: number;
    checks: {
      details: string[];
      score: number;
      reason: string;
      name: string;
      documentation: {
        url: string;
        short: string;
      };
    }[];
    metadata: string[];
  };
  reportFileName: string;
  reportDigestSet: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` ".*".
     */
    [k: string]: string;
  };
}
