// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type filetraceSyscallPendingOpen struct {
	_        structs.HostLayout
	Filename uint64
	Dfd      int32
	_        [4]byte
	Error    int64
	Path     [256]int8
}

// loadFiletraceSyscall returns the embedded CollectionSpec for filetraceSyscall.
func loadFiletraceSyscall() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FiletraceSyscallBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load filetraceSyscall: %w", err)
	}

	return spec, err
}

// loadFiletraceSyscallObjects loads filetraceSyscall and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*filetraceSyscallObjects
//	*filetraceSyscallPrograms
//	*filetraceSyscallMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFiletraceSyscallObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFiletraceSyscall()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// filetraceSyscallSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filetraceSyscallSpecs struct {
	filetraceSyscallProgramSpecs
	filetraceSyscallMapSpecs
	filetraceSyscallVariableSpecs
}

// filetraceSyscallProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filetraceSyscallProgramSpecs struct {
	TraceOpen             *ebpf.ProgramSpec `ebpf:"trace_open"`
	TraceOpenExit         *ebpf.ProgramSpec `ebpf:"trace_open_exit"`
	TraceOpenat           *ebpf.ProgramSpec `ebpf:"trace_openat"`
	TraceOpenat2          *ebpf.ProgramSpec `ebpf:"trace_openat2"`
	TraceOpenat2Exit      *ebpf.ProgramSpec `ebpf:"trace_openat2_exit"`
	TraceOpenatExit       *ebpf.ProgramSpec `ebpf:"trace_openat_exit"`
	TraceSchedProcessExec *ebpf.ProgramSpec `ebpf:"trace_sched_process_exec"`
	TraceSchedProcessExit *ebpf.ProgramSpec `ebpf:"trace_sched_process_exit"`
}

// filetraceSyscallMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filetraceSyscallMapSpecs struct {
	Events       *ebpf.MapSpec `ebpf:"events"`
	PendingOpens *ebpf.MapSpec `ebpf:"pending_opens"`
}

// filetraceSyscallVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filetraceSyscallVariableSpecs struct {
	TargetCgroupId *ebpf.VariableSpec `ebpf:"target_cgroup_id"`
}

// filetraceSyscallObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFiletraceSyscallObjects or ebpf.CollectionSpec.LoadAndAssign.
type filetraceSyscallObjects struct {
	filetraceSyscallPrograms
	filetraceSyscallMaps
	filetraceSyscallVariables
}

func (o *filetraceSyscallObjects) Close() error {
	return _FiletraceSyscallClose(
		&o.filetraceSyscallPrograms,
		&o.filetraceSyscallMaps,
	)
}

// filetraceSyscallMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFiletraceSyscallObjects or ebpf.CollectionSpec.LoadAndAssign.
type filetraceSyscallMaps struct {
	Events       *ebpf.Map `ebpf:"events"`
	PendingOpens *ebpf.Map `ebpf:"pending_opens"`
}

func (m *filetraceSyscallMaps) Close() error {
	return _FiletraceSyscallClose(
		m.Events,
		m.PendingOpens,
	)
}

// filetraceSyscallVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFiletraceSyscallObjects or ebpf.CollectionSpec.LoadAndAssign.
type filetraceSyscallVariables struct {
	TargetCgroupId *ebpf.Variable `ebpf:"target_cgroup_id"`
}

// filetraceSyscallPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFiletraceSyscallObjects or ebpf.CollectionSpec.LoadAndAssign.
type filetraceSyscallPrograms struct {
	TraceOpen             *ebpf.Program `ebpf:"trace_open"`
	TraceOpenExit         *ebpf.Program `ebpf:"trace_open_exit"`
	TraceOpenat           *ebpf.Program `ebpf:"trace_openat"`
	TraceOpenat2          *ebpf.Program `ebpf:"trace_openat2"`
	TraceOpenat2Exit      *ebpf.Program `ebpf:"trace_openat2_exit"`
	TraceOpenatExit       *ebpf.Program `ebpf:"trace_openat_exit"`
	TraceSchedProcessExec *ebpf.Program `ebpf:"trace_sched_process_exec"`
	TraceSchedProcessExit *ebpf.Program `ebpf:"trace_sched_process_exit"`
}

func (p *filetraceSyscallPrograms) Close() error {
	return _FiletraceSyscallClose(
		p.TraceOpen,
		p.TraceOpenExit,
		p.TraceOpenat,
		p.TraceOpenat2,
		p.TraceOpenat2Exit,
		p.TraceOpenatExit,
		p.TraceSchedProcessExec,
		p.TraceSchedProcessExit,
	)
}

func _FiletraceSyscallClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed filetracesyscall_bpfel.o
var _FiletraceSyscallBytes []byte
