// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type connectCgroupAllowlistKey struct {
	_        structs.HostLayout
	CgroupId uint64
}

type connectCommAllowlistKey struct {
	_    structs.HostLayout
	Comm [16]int8
}

type connectOrigDstKey struct {
	_          structs.HostLayout
	SockCookie uint64
}

type connectOrigDstKeyV6 struct {
	_          structs.HostLayout
	SockCookie uint64
}

type connectOrigDstVal struct {
	_        structs.HostLayout
	OrigIp   uint32
	OrigPort uint16
	Pad      uint16
	CgroupId uint64
	Pid      uint32
	Pad2     uint32
	Comm     [16]int8
}

type connectOrigDstValV6 struct {
	_        structs.HostLayout
	OrigIp   [16]uint8
	OrigPort uint16
	Pad      uint16
	Pad1     uint32
	CgroupId uint64
	Pid      uint32
	Pad2     uint32
	Comm     [16]int8
}

type connectTidAllowlistKey struct {
	_   structs.HostLayout
	Tid uint32
}

type connectTidAllowlistVal struct {
	_             structs.HostLayout
	NestedAllowed uint8
}

type connectTupleKey struct {
	_          structs.HostLayout
	LocalIp    uint32
	LocalPort  uint16
	Pad1       uint16
	RemoteIp   uint32
	RemotePort uint16
	Pad2       uint16
}

type connectTupleKeyV6 struct {
	_          structs.HostLayout
	LocalIp    [16]uint8
	LocalPort  uint16
	Pad1       uint16
	RemoteIp   [16]uint8
	RemotePort uint16
	Pad2       uint16
}

type connectTupleVal struct {
	_            structs.HostLayout
	ClientCookie uint64
}

// loadConnect returns the embedded CollectionSpec for connect.
func loadConnect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ConnectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load connect: %w", err)
	}

	return spec, err
}

// loadConnectObjects loads connect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*connectObjects
//	*connectPrograms
//	*connectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadConnectObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadConnect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// connectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectSpecs struct {
	connectProgramSpecs
	connectMapSpecs
	connectVariableSpecs
}

// connectProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectProgramSpecs struct {
	InterceptConnect4 *ebpf.ProgramSpec `ebpf:"intercept_connect4"`
	InterceptConnect6 *ebpf.ProgramSpec `ebpf:"intercept_connect6"`
}

// connectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectMapSpecs struct {
	CgroupAllowlist    *ebpf.MapSpec `ebpf:"cgroup_allowlist"`
	CommAllowlist      *ebpf.MapSpec `ebpf:"comm_allowlist"`
	OrigDstMap         *ebpf.MapSpec `ebpf:"orig_dst_map"`
	OrigDstMapV6       *ebpf.MapSpec `ebpf:"orig_dst_map_v6"`
	PendingExecs       *ebpf.MapSpec `ebpf:"pending_execs"`
	TidAllowlist       *ebpf.MapSpec `ebpf:"tid_allowlist"`
	TupleToCookieMap   *ebpf.MapSpec `ebpf:"tuple_to_cookie_map"`
	TupleToCookieMapV6 *ebpf.MapSpec `ebpf:"tuple_to_cookie_map_v6"`
}

// connectVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectVariableSpecs struct {
	HostNetnsInum *ebpf.VariableSpec `ebpf:"host_netns_inum"`
	ProxyIp       *ebpf.VariableSpec `ebpf:"proxy_ip"`
	ProxyPort     *ebpf.VariableSpec `ebpf:"proxy_port"`
}

// connectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectObjects struct {
	connectPrograms
	connectMaps
	connectVariables
}

func (o *connectObjects) Close() error {
	return _ConnectClose(
		&o.connectPrograms,
		&o.connectMaps,
	)
}

// connectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectMaps struct {
	CgroupAllowlist    *ebpf.Map `ebpf:"cgroup_allowlist"`
	CommAllowlist      *ebpf.Map `ebpf:"comm_allowlist"`
	OrigDstMap         *ebpf.Map `ebpf:"orig_dst_map"`
	OrigDstMapV6       *ebpf.Map `ebpf:"orig_dst_map_v6"`
	PendingExecs       *ebpf.Map `ebpf:"pending_execs"`
	TidAllowlist       *ebpf.Map `ebpf:"tid_allowlist"`
	TupleToCookieMap   *ebpf.Map `ebpf:"tuple_to_cookie_map"`
	TupleToCookieMapV6 *ebpf.Map `ebpf:"tuple_to_cookie_map_v6"`
}

func (m *connectMaps) Close() error {
	return _ConnectClose(
		m.CgroupAllowlist,
		m.CommAllowlist,
		m.OrigDstMap,
		m.OrigDstMapV6,
		m.PendingExecs,
		m.TidAllowlist,
		m.TupleToCookieMap,
		m.TupleToCookieMapV6,
	)
}

// connectVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectVariables struct {
	HostNetnsInum *ebpf.Variable `ebpf:"host_netns_inum"`
	ProxyIp       *ebpf.Variable `ebpf:"proxy_ip"`
	ProxyPort     *ebpf.Variable `ebpf:"proxy_port"`
}

// connectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectPrograms struct {
	InterceptConnect4 *ebpf.Program `ebpf:"intercept_connect4"`
	InterceptConnect6 *ebpf.Program `ebpf:"intercept_connect6"`
}

func (p *connectPrograms) Close() error {
	return _ConnectClose(
		p.InterceptConnect4,
		p.InterceptConnect6,
	)
}

func _ConnectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed connect_bpfel.o
var _ConnectBytes []byte
