// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type sockopsCgroupAllowlistKey struct {
	_        structs.HostLayout
	CgroupId uint64
}

type sockopsCommAllowlistKey struct {
	_    structs.HostLayout
	Comm [16]int8
}

type sockopsInjectionTimeVal struct {
	_             structs.HostLayout
	InjectionTime uint64
}

type sockopsOrigDstKey struct {
	_          structs.HostLayout
	SockCookie uint64
}

type sockopsOrigDstKeyV6 struct {
	_          structs.HostLayout
	SockCookie uint64
}

type sockopsOrigDstVal struct {
	_        structs.HostLayout
	OrigIp   uint32
	OrigPort uint16
	Pad      uint16
	CgroupId uint64
	Pid      uint32
	Pad2     uint32
	Comm     [16]int8
}

type sockopsOrigDstValV6 struct {
	_        structs.HostLayout
	OrigIp   [16]uint8
	OrigPort uint16
	Pad      uint16
	Pad1     uint32
	CgroupId uint64
	Pid      uint32
	Pad2     uint32
	Comm     [16]int8
}

type sockopsPidAllowlistKey struct {
	_   structs.HostLayout
	Pid uint32
}

type sockopsPidAllowlistVal struct {
	_             structs.HostLayout
	NestedAllowed uint8
}

type sockopsTupleKey struct {
	_          structs.HostLayout
	LocalIp    uint32
	LocalPort  uint16
	Pad1       uint16
	RemoteIp   uint32
	RemotePort uint16
	Pad2       uint16
}

type sockopsTupleKeyV6 struct {
	_          structs.HostLayout
	LocalIp    [16]uint8
	LocalPort  uint16
	Pad1       uint16
	RemoteIp   [16]uint8
	RemotePort uint16
	Pad2       uint16
}

type sockopsTupleVal struct {
	_            structs.HostLayout
	ClientCookie uint64
}

// loadSockops returns the embedded CollectionSpec for sockops.
func loadSockops() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SockopsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load sockops: %w", err)
	}

	return spec, err
}

// loadSockopsObjects loads sockops and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*sockopsObjects
//	*sockopsPrograms
//	*sockopsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSockopsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSockops()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// sockopsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockopsSpecs struct {
	sockopsProgramSpecs
	sockopsMapSpecs
	sockopsVariableSpecs
}

// sockopsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockopsProgramSpecs struct {
	TcpSockops *ebpf.ProgramSpec `ebpf:"tcp_sockops"`
}

// sockopsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockopsMapSpecs struct {
	CgroupAllowlist    *ebpf.MapSpec `ebpf:"cgroup_allowlist"`
	CommAllowlist      *ebpf.MapSpec `ebpf:"comm_allowlist"`
	InjectionTimeMap   *ebpf.MapSpec `ebpf:"injection_time_map"`
	OrigDstMap         *ebpf.MapSpec `ebpf:"orig_dst_map"`
	OrigDstMapV6       *ebpf.MapSpec `ebpf:"orig_dst_map_v6"`
	PidAllowlist       *ebpf.MapSpec `ebpf:"pid_allowlist"`
	TupleToCookieMap   *ebpf.MapSpec `ebpf:"tuple_to_cookie_map"`
	TupleToCookieMapV6 *ebpf.MapSpec `ebpf:"tuple_to_cookie_map_v6"`
}

// sockopsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockopsVariableSpecs struct {
	HostNetnsInum *ebpf.VariableSpec `ebpf:"host_netns_inum"`
}

// sockopsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockopsObjects struct {
	sockopsPrograms
	sockopsMaps
	sockopsVariables
}

func (o *sockopsObjects) Close() error {
	return _SockopsClose(
		&o.sockopsPrograms,
		&o.sockopsMaps,
	)
}

// sockopsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockopsMaps struct {
	CgroupAllowlist    *ebpf.Map `ebpf:"cgroup_allowlist"`
	CommAllowlist      *ebpf.Map `ebpf:"comm_allowlist"`
	InjectionTimeMap   *ebpf.Map `ebpf:"injection_time_map"`
	OrigDstMap         *ebpf.Map `ebpf:"orig_dst_map"`
	OrigDstMapV6       *ebpf.Map `ebpf:"orig_dst_map_v6"`
	PidAllowlist       *ebpf.Map `ebpf:"pid_allowlist"`
	TupleToCookieMap   *ebpf.Map `ebpf:"tuple_to_cookie_map"`
	TupleToCookieMapV6 *ebpf.Map `ebpf:"tuple_to_cookie_map_v6"`
}

func (m *sockopsMaps) Close() error {
	return _SockopsClose(
		m.CgroupAllowlist,
		m.CommAllowlist,
		m.InjectionTimeMap,
		m.OrigDstMap,
		m.OrigDstMapV6,
		m.PidAllowlist,
		m.TupleToCookieMap,
		m.TupleToCookieMapV6,
	)
}

// sockopsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockopsVariables struct {
	HostNetnsInum *ebpf.Variable `ebpf:"host_netns_inum"`
}

// sockopsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockopsPrograms struct {
	TcpSockops *ebpf.Program `ebpf:"tcp_sockops"`
}

func (p *sockopsPrograms) Close() error {
	return _SockopsClose(
		p.TcpSockops,
	)
}

func _SockopsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sockops_bpfel.o
var _SockopsBytes []byte
