// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type task_trackerCgroupAllowlistKey struct {
	_        structs.HostLayout
	CgroupId uint64
}

type task_trackerCommAllowlistKey struct {
	_    structs.HostLayout
	Comm [16]int8
}

type task_trackerOrigDstKey struct {
	_          structs.HostLayout
	SockCookie uint64
}

type task_trackerOrigDstKeyV6 struct {
	_          structs.HostLayout
	SockCookie uint64
}

type task_trackerOrigDstVal struct {
	_        structs.HostLayout
	OrigIp   uint32
	OrigPort uint16
	Pad      uint16
	CgroupId uint64
	Pid      uint32
	Pad2     uint32
	Comm     [16]int8
}

type task_trackerOrigDstValV6 struct {
	_        structs.HostLayout
	OrigIp   [16]uint8
	OrigPort uint16
	Pad      uint16
	Pad1     uint32
	CgroupId uint64
	Pid      uint32
	Pad2     uint32
	Comm     [16]int8
}

type task_trackerTidAllowlistKey struct {
	_   structs.HostLayout
	Tid uint32
}

type task_trackerTidAllowlistVal struct {
	_             structs.HostLayout
	NestedAllowed uint8
}

type task_trackerTupleKey struct {
	_          structs.HostLayout
	LocalIp    uint32
	LocalPort  uint16
	Pad1       uint16
	RemoteIp   uint32
	RemotePort uint16
	Pad2       uint16
}

type task_trackerTupleKeyV6 struct {
	_          structs.HostLayout
	LocalIp    [16]uint8
	LocalPort  uint16
	Pad1       uint16
	RemoteIp   [16]uint8
	RemotePort uint16
	Pad2       uint16
}

type task_trackerTupleVal struct {
	_            structs.HostLayout
	ClientCookie uint64
}

// loadTask_tracker returns the embedded CollectionSpec for task_tracker.
func loadTask_tracker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Task_trackerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load task_tracker: %w", err)
	}

	return spec, err
}

// loadTask_trackerObjects loads task_tracker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*task_trackerObjects
//	*task_trackerPrograms
//	*task_trackerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTask_trackerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTask_tracker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// task_trackerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type task_trackerSpecs struct {
	task_trackerProgramSpecs
	task_trackerMapSpecs
	task_trackerVariableSpecs
}

// task_trackerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type task_trackerProgramSpecs struct {
	HandleSchedProcessExec *ebpf.ProgramSpec `ebpf:"handle_sched_process_exec"`
	HandleSchedProcessExit *ebpf.ProgramSpec `ebpf:"handle_sched_process_exit"`
	HandleSchedProcessFork *ebpf.ProgramSpec `ebpf:"handle_sched_process_fork"`
	SysEnterExecve         *ebpf.ProgramSpec `ebpf:"sys_enter_execve"`
	SysEnterExecveat       *ebpf.ProgramSpec `ebpf:"sys_enter_execveat"`
	SysExitExecve          *ebpf.ProgramSpec `ebpf:"sys_exit_execve"`
	SysExitExecveat        *ebpf.ProgramSpec `ebpf:"sys_exit_execveat"`
}

// task_trackerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type task_trackerMapSpecs struct {
	CgroupAllowlist    *ebpf.MapSpec `ebpf:"cgroup_allowlist"`
	CommAllowlist      *ebpf.MapSpec `ebpf:"comm_allowlist"`
	OrigDstMap         *ebpf.MapSpec `ebpf:"orig_dst_map"`
	OrigDstMapV6       *ebpf.MapSpec `ebpf:"orig_dst_map_v6"`
	PendingExecs       *ebpf.MapSpec `ebpf:"pending_execs"`
	TidAllowlist       *ebpf.MapSpec `ebpf:"tid_allowlist"`
	TupleToCookieMap   *ebpf.MapSpec `ebpf:"tuple_to_cookie_map"`
	TupleToCookieMapV6 *ebpf.MapSpec `ebpf:"tuple_to_cookie_map_v6"`
}

// task_trackerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type task_trackerVariableSpecs struct {
}

// task_trackerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTask_trackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type task_trackerObjects struct {
	task_trackerPrograms
	task_trackerMaps
	task_trackerVariables
}

func (o *task_trackerObjects) Close() error {
	return _Task_trackerClose(
		&o.task_trackerPrograms,
		&o.task_trackerMaps,
	)
}

// task_trackerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTask_trackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type task_trackerMaps struct {
	CgroupAllowlist    *ebpf.Map `ebpf:"cgroup_allowlist"`
	CommAllowlist      *ebpf.Map `ebpf:"comm_allowlist"`
	OrigDstMap         *ebpf.Map `ebpf:"orig_dst_map"`
	OrigDstMapV6       *ebpf.Map `ebpf:"orig_dst_map_v6"`
	PendingExecs       *ebpf.Map `ebpf:"pending_execs"`
	TidAllowlist       *ebpf.Map `ebpf:"tid_allowlist"`
	TupleToCookieMap   *ebpf.Map `ebpf:"tuple_to_cookie_map"`
	TupleToCookieMapV6 *ebpf.Map `ebpf:"tuple_to_cookie_map_v6"`
}

func (m *task_trackerMaps) Close() error {
	return _Task_trackerClose(
		m.CgroupAllowlist,
		m.CommAllowlist,
		m.OrigDstMap,
		m.OrigDstMapV6,
		m.PendingExecs,
		m.TidAllowlist,
		m.TupleToCookieMap,
		m.TupleToCookieMapV6,
	)
}

// task_trackerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTask_trackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type task_trackerVariables struct {
}

// task_trackerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTask_trackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type task_trackerPrograms struct {
	HandleSchedProcessExec *ebpf.Program `ebpf:"handle_sched_process_exec"`
	HandleSchedProcessExit *ebpf.Program `ebpf:"handle_sched_process_exit"`
	HandleSchedProcessFork *ebpf.Program `ebpf:"handle_sched_process_fork"`
	SysEnterExecve         *ebpf.Program `ebpf:"sys_enter_execve"`
	SysEnterExecveat       *ebpf.Program `ebpf:"sys_enter_execveat"`
	SysExitExecve          *ebpf.Program `ebpf:"sys_exit_execve"`
	SysExitExecveat        *ebpf.Program `ebpf:"sys_exit_execveat"`
}

func (p *task_trackerPrograms) Close() error {
	return _Task_trackerClose(
		p.HandleSchedProcessExec,
		p.HandleSchedProcessExit,
		p.HandleSchedProcessFork,
		p.SysEnterExecve,
		p.SysEnterExecveat,
		p.SysExitExecve,
		p.SysExitExecveat,
	)
}

func _Task_trackerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed task_tracker_bpfel.o
var _Task_trackerBytes []byte
