name: Build Witness CLI Test

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches: [ main, 'feat/*' ]

jobs:
  build-witness:
    name: Build Witness CLI with PR SHA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Build Witness CLI with current SHA
        id: build-witness
        run: |
          # Create temporary directory
          WITNESS_TMP_DIR=/tmp/witness-build-test
          rm -rf $WITNESS_TMP_DIR
          mkdir -p $WITNESS_TMP_DIR
          
          # Get current SHA
          CURRENT_SHA=$(git rev-parse HEAD)
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          GO_WITNESS_MODULE=github.com/in-toto/go-witness
          
          echo "Using go-witness SHA: $CURRENT_SHA"
          echo "Current branch: $CURRENT_BRANCH"
          
          # Clone witness repository
          git clone https://github.com/in-toto/witness.git $WITNESS_TMP_DIR
          cd $WITNESS_TMP_DIR
          
          # Try to checkout a matching branch in witness repo if it exists
          # Otherwise stay on main
          WITNESS_BRANCH="main"
          if [ "$CURRENT_BRANCH" != "main" ] && [ "$CURRENT_BRANCH" != "HEAD" ]; then
            git fetch origin $CURRENT_BRANCH || true
            if git show-ref --verify --quiet refs/remotes/origin/$CURRENT_BRANCH; then
              git checkout $CURRENT_BRANCH
              WITNESS_BRANCH=$CURRENT_BRANCH
              echo "Using matching witness branch: $WITNESS_BRANCH"
            else
              echo "No matching branch found in witness repo, using main"
            fi
          fi
          
          # Update go-witness dependency to use our current SHA
          go get $GO_WITNESS_MODULE@$CURRENT_SHA
          go mod tidy
          
          # Create artifact directory
          mkdir -p /tmp/witness-artifacts
          
          # Build witness for the current platform (Linux AMD64)
          echo "Building for Linux AMD64..."
          go build -o witness .
          
          echo "Witness successfully built with:"
          echo "- go-witness SHA: $CURRENT_SHA"
          echo "- witness branch: $WITNESS_BRANCH"
          
          # Verify the binary works
          ./witness version
          
          # Copy to artifacts directory
          cp ./witness /tmp/witness-artifacts/witness-linux-amd64
          
          # Build for other platforms
          echo "Building for macOS AMD64..."
          GOOS=darwin GOARCH=amd64 go build -o /tmp/witness-artifacts/witness-darwin-amd64 .
          
          echo "Building for macOS ARM64..."
          GOOS=darwin GOARCH=arm64 go build -o /tmp/witness-artifacts/witness-darwin-arm64 .
          
          echo "Building for Windows AMD64..."
          GOOS=windows GOARCH=amd64 go build -o /tmp/witness-artifacts/witness-windows-amd64.exe .
          
          # Set output variables
          echo "witness_dir=/tmp/witness-artifacts" >> $GITHUB_OUTPUT
          echo "sha_short=${CURRENT_SHA:0:7}" >> $GITHUB_OUTPUT
          echo "witness_branch=$WITNESS_BRANCH" >> $GITHUB_OUTPUT

      - name: Upload Witness Binary
        uses: actions/upload-artifact@v4
        with:
          name: witness-cli-${{ steps.build-witness.outputs.sha_short }}-witness-${{ steps.build-witness.outputs.witness_branch }}
          path: ${{ steps.build-witness.outputs.witness_dir }}/*
          retention-days: 7
          if-no-files-found: error