name: Docgen
on:
  workflow_dispatch:
  push:
    branches: ["main", "release-*"]
  pull_request:
permissions:
  contents: read

jobs:
  verify-schema:
    name: Verify Schema
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"
      - run: docker run -v ./:/app -w /app --entrypoint ./schemagen/verify.sh cgr.dev/chainguard/go
