name: Docgen
on:
  workflow_dispatch:
  push:
    branches: ["main", "release-*"]
  pull_request:
permissions:
  contents: read

jobs:
  verify-schema:
    name: Verify Schema
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: "go.mod"
      - run: docker run -v ./:/app -w /app --entrypoint ./schemagen/verify.sh cgr.dev/chainguard/go
